### ISSUE TITLE
Compatibility with gradle 7

### ISSUE THREAD

**Issue by bmarty** [LikeTheSalad/android-string-reference#11]
Hi,

I'm trying to migrate my project to gradle 7 and I get an error with your plugin:

```
* What went wrong:
A problem was found with the configuration of task ':vector:gatherGplayDebugRawStrings' (type 'GatherRawStringsTask').
  - Type 'GatherRawStringsTask' property 'gatherRawStringsAction' is missing an input or output annotation.
    
    Reason: A property without annotation isn't considered during up-to-date checking.
    
    Possible solutions:
      1. Add an input or output annotation.
      2. Mark it as @Internal.
    
    Please refer to https://docs.gradle.org/7.0/userguide/validation_problems.html#missing_annotation for more details about this problem.
```

https://docs.gradle.org/7.0/userguide/validation_problems.html#missing_annotation

Full logs of error can be found here: https://buildkite.com/matrix-dot-org/element-android/builds/1993

Thanks!

**Comment by LikeTheSalad** [comment]
Hi @bmarty many thanks for your feedback!

I've just released a new version `1.2.2` where this issue should be fixed. Please let me know if that's not the case.

Regards,
Cesar

**Comment by bmarty** [comment]
Hello @LikeTheSalad , it seems fine on my computer, the CI will confirm it (https://github.com/vector-im/element-android/pull/3152). Thanks for the fast update!

**Comment by LikeTheSalad** [comment]
Cheers! I'm going to close this because it seems like it's passing in your CI too, though please re-open it if that's not the case 👍
