### ISSUE TITLE
Not Working with Gradle 7.0.2

### ISSUE THREAD

**Issue by khem-lang** [LikeTheSalad/android-string-reference#13]
Hi,
        My Gradle version is 7.02 and  com.likethesalad.android:string-reference:1.2.1 is not working it throw a blow error
 
 Could not GET 'https://dl.google.com/dl/android/maven2/com/likethesalad/android/string-reference/1.2.2/string-reference-1.2.2.pom'. Received status code 405 from server: Method Not Allowed.

Thanks

**Comment by LikeTheSalad** [comment]
Hi @khem-lang - It seems like you are missing the `mavenCentral()` repo in your buildscript.repositories block in the root build.gradle file. If not sure about where you should place it, please show me how your root build.gradle buildscript block looks like and I can let you know based on your case where it should go.

Please let me know how it goes 👍

**Comment by GLmaksym** [comment]
Hello @LikeTheSalad I am getting this error 
```
A problem was found with the configuration of task ':mobile:gatherProductionDebugRawStrings' (type 'GatherRawStringsTask').
  - Type 'com.likethesalad.placeholder.tasks.GatherRawStringsTask' property 'gatherRawStringsAction' is missing an input or output annotation.
```

Any ideas?

**Comment by LikeTheSalad** [comment]
Hi @khem-lang - yes, it sounds like an issue for older versions, please use the latest one `1.2.2`.
