### ISSUE TITLE
Plugin is not applied to modules (library projects)

### ISSUE THREAD

**Issue by danaimset** [LikeTheSalad/android-string-reference#2]
There is not way to generate strings from templates inside submodules (com.android.library)

**Comment by LikeTheSalad** [comment]
Hi @danaimset, that's as expected at the moment, only strings in the project are used and the ones in the project's dependencies are ignored. I'm planning to add support for strings in dependencies too for the next release.

**Comment by LikeTheSalad** [comment]
Hi @danaimset you can now use strings from your app's dependencies by turning on in your app's `build.gradle` file the new flag `useDependenciesRes` added on `1.2.0` like so:

```groovy
stringXmlReference {
    useDependenciesRes = true
}
```
Hope that gets it sorted for you.
Cheers.

**Comment by Voto** [comment]
@LikeTheSalad cool, that last option makes the lib feasible for our project. We will try It out to generate URIs to be used by android jetpack navigation deeplink property. making uris <scheme-by-flavor>://<host_name>

**Comment by LikeTheSalad** [comment]
Glad to hear it @Voto I hope it works as you need it, in case you find a problem please raise a ticket 🙂
