### ISSUE TITLE
Is this plugin works with last AS 4.0 and last Gradle plugin?

### ISSUE THREAD

**Issue by francescogatto** [LikeTheSalad/android-string-reference#3]
I tried to use it, ma is not working

Thanks

**Comment by LikeTheSalad** [comment]
Hi @francescogatto - I just tried with AS 4.0.1, Android build plugin 4.0.1, and Gradle wrapper 6.1.1 and it worked for me. I'm going to need a bit more details such as:

- Have you added the changes on both root and app build.gradle files?
- Are you using it after the plugin declaration for `com.android.application`?
- After creating your template, have you built your project before looking for the generated strings?
- What versions of the android build plugin and gradle wrapper are you using?

Thanks.

**Comment by LikeTheSalad** [comment]
I'll close this issue due to inactivity, please reopen if you keep seeing the issue and if you can provide the details asked above, it will help sort it out.

Thanks.
