### ISSUE TITLE
Plugin don`t worked in Dynamic Feature modules

### ISSUE THREAD

**Issue by Fantastic12** [LikeTheSalad/android-string-reference#8]
If in app has dynamic feature module, plugin not work

**Comment by LikeTheSalad** [comment]
Hi @Fantastic12, sorry for the delay! - Yes you're right, the resolving strings process works at compile time on application modules, and a dynamic feature is downloaded after the app is compiled/installed, therefore it is not possible to make it work with a dynamic feature, unfortunately.

**Comment by burhankhanzada** [comment]
what about install time dfm included with apk
